# Generated by Django 2.1.5 on 2019-01-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fb_insight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_page', models.CharField(max_length=200)),
                ('fb_metric', models.CharField(max_length=100)),
                ('fb_since', models.IntegerField()),
                ('fb_until', models.IntegerField()),
                ('fb_token', models.CharField(max_length=200)),
            ],
        ),
    ]
