# Generated by Django 2.1.5 on 2019-01-28 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fb_insight',
            old_name='fb_since',
            new_name='fb_date',
        ),
        migrations.RemoveField(
            model_name='fb_insight',
            name='fb_until',
        ),
    ]
