# Generated by Django 2.1.5 on 2019-01-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_auto_20190128_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='fb_insight',
            name='fb_value',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
