# Generated by Django 2.1.5 on 2019-01-30 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0004_auto_20190130_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fb_insight',
            name='fb_value',
        ),
    ]
