# Generated by Django 2.1.5 on 2019-01-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0005_remove_fb_insight_fb_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='fb_insight',
            name='fb_value',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
