# Generated by Django 2.1.5 on 2019-02-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0007_auto_20190130_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='fb_insight',
            name='fb_page_name',
            field=models.CharField(default='디폴트', max_length=200),
        ),
    ]
