# Generated by Django 2.1.5 on 2019-02-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0008_fb_insight_fb_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fb_insight',
            name='fb_page_name',
            field=models.CharField(max_length=200),
        ),
    ]
